apiVersion: v1
kind: Pod
metadata:
  name: clone-git-repo
  labels:
    name: clone-git-repo
spec:
  initContainers:
    - name: init-container
      image: ubuntu
      volumeMounts:
        - name: storage
          mountPath: /storage
      command:
      - "/bin/bash"
      args:
      - "-c"
      - "echo 'tutaj udaje ze klonuje repo'; echo hehhe > /storage/index.html"
  containers:
  - name: clone-git-repo
    image: nginx
    resources: {}
    volumeMounts:
    - name: storage
      mountPath: /usr/share/nginx/html/
    ports:
      - containerPort: 80
  volumes:
    - name: storage
      emptyDir: {}
