#!/bin/sh
echo "================ DIFF3 ==================" >> /home/jgrycz/dupa
echo "$@" >> /home/jgrycz/dupa
echo "=========================================" >> /home/jgrycz/dupa
kdiff3 "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "$10"
