apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-data
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /tmp/volumes/ss/
