apiVersion: v1
kind: Service
metadata:
  name: test-ss
spec:
  selector:
    app: test-ss
  clusterIP: None
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-ss
spec:
  serviceName: test-ss
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: test-ss
  template:
    metadata:
      labels:
        app: test-ss
        version: v3
    spec:
      initContainers:
        - name: init-actions
          image: busybox
          command: ['/bin/sh', "-c", "echo Siema Eniu > /data/index.html"]
          volumeMounts:
            - name: test-ss-pvc
              mountPath: /data
      containers:
      - name: test-ss
        image: nginx
        resources: {}
        volumeMounts:
          - name: test-ss-pvc
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: test-ss-pvc
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Mi
