apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["echo"]
    args: ["Pierwsza zmienna $(GREETING), druga  $(NAME)"]
    env:
    - name: GREETING
      value: "Warm greetings to"
    - name: NAME
      value: Kubernetes
    resources: {}
