apiVersion: v1
kind: Pod
metadata:
  name: helloapp
  labels:
    name: helloapp
spec:
  containers:
  - name: helloapp
    image: poznajkubernetes/helloapp:8888
  - name: kuard
    image: poznajkubernetes/kuard
