apiVersion: v1
kind: Pod
metadata:
  name: lifecycle
  labels:
    name: lifecycle
spec:
  restartPolicy: Never
  containers:
  - name: lifecycle
    image: busybox
    command: ['sh', '-c', 'echo $(date +%s): START >> /loap/timing.txt; sleep 30; echo $(date +%s): END >> /loap/timing.txt;']
    volumeMounts:
      - mountPath: /loap
        name: timing
    resources:
      requests:
        memory: "4Gi"
        cpu: 4.0
  volumes:
    - name: timing
      hostPath:
          path: /c/temp
