apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    name: test
spec:
  containers:
  - name: test
    image: busybox
    resources: {}
    command: ["/bin/sh", "-c", "while true; do echo $(date +%T.%s): Aplikacja: $(APP_NAME), POD: $(THIS_POD_NAME); sleep $(SLEEP_TIME); done"]
    env:
    - name: APP_NAME
      value: "TEST-APP"
    - name: SLEEP_TIME
      value: "10"
    - name: THIS_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
