apiVersion: v1
kind: Pod
metadata:
  name: pkad1
  labels:
    app: ui
    env: test
spec:
  containers:
  - name: pkad1
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
