apiVersion: v1
kind: Pod
metadata:
  name: pkad3
spec:
  containers:
  - name: pkad3
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
