apiVersion: v1
kind: Pod
metadata:
  name: pkad
  labels:
    name: pkad
spec:
  containers:
  - name: pkad
    image: poznajkubernetes/pkad
    resources: {}
    env:
      - name: CM1_ENV1
        valueFrom:
            configMapKeyRef:
              key: 123_TESTING
              name: cm-01
      - name: CM2_ENV1
        valueFrom:
            configMapKeyRef:
              key: config1.cfg
              name: cm-02
      - name: CM1_ENV2
        valueFrom:
            configMapKeyRef:
              key: TESTING 
              name: cm-01
      - name: CM2_ENV2
        valueFrom:
            configMapKeyRef:
              key: konfig_2
              name: cm-02
      - name: CM1_ENV3
        valueFrom:
            configMapKeyRef:
              key: TESTING-123
              name: cm-01
    ports:
      - containerPort: 8080
