apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  labels:
    app: demo-rs
    tier: test-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: test-rs
  template:
    metadata:
      labels:
        tier: test-rs
        env: stage
        name: test-hehe
        poznaj: kubernetes
    spec:
      containers:
        - name: pkad
          image: poznajkubernetes/pkad:green
