apiVersion: v1
kind: Pod
metadata:
  name: pkad-recommended
  annotations:
    poznajk8s/name: pkad
    poznajk8s/instance: pkad-example
    poznajk8s/version: "1.0.0"
    poznajk8s/component: ui
    poznajk8s/part-of: pkad
    poznajk8s/managed-by: devops
spec:
  containers:
  - name: pkad
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
