apiVersion: v1
kind: Pod
metadata:
  name: pkad-recommended
  labels:
    app.kubernetes.io/name: pkad
    app.kubernetes.io/instance: pkad-example
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: pkad
    app.kubernetes.io/managed-by: devops

spec:
  containers:
  - name: pkad
    image: poznajkubernetes/pkad
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
