apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkad
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: pkad
  template:
    metadata:
      labels:
        app: pkad
    spec:
      containers:
      - name: pkad
        image: poznajkubernetes/pkad:blue
        env:
        - name: version
          value: "v2.0.0"
        resources: {}
        ports:
        - containerPort: 8080
