apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: multi-container
spec:
  containers:
  - name: first-container
    image: busybox
    command: ["sh", "-c", "ping localhost;"]
  - name: second-container
    image: poznajkubernetes/helloapp:multi