apiVersion: v1
kind: Pod
metadata:
  name: demo-private-registry
  labels:
    name: demo-private-registry
spec:
  containers:
  - name: demo-private-registry
    image: jgrycz/helloapp:dev
    resources: {}
    ports:
      - containerPort: 8080
  imagePullSecrets:
    - name: regcred
