apiVersion: v1
kind: Service
metadata:
  name: external-web
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-web
subsets:
  - addresses:
    - ip: 1.1.1.1
    ports:
      - port: 80
        name: http