apiVersion: v1
kind: Service
metadata:
  name: helloapp-port
spec:
  selector:
    app: helloapp
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 8080
    protocol: TCP
  - port: 8090
    name: http-8090
    targetPort: 8080
    protocol: TCP