apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
    - name: storage-volume
      emptyDir: {}
  initContainers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo "<h1>Czołem!</h1>" > /storage/index.html;']
      volumeMounts:
        - mountPath: /storage/
          name: storage-volume
  containers:
  - name: myapp
    image: nginx
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: storage-volume       
  - name: tools
    image: busybox
    resources: {}
    command: ['sh', '-c', 'while true; do echo "I am still alive"; sleep 10; done;']
