apiVersion: v1
kind: Pod
metadata:
  name: bb
  labels:
    name: bb
spec:
  restartPolicy: Never
  containers:
  - name: bb
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
