apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox:glibc
    name: busybox
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
    command:
    - "sleep"
    - "35"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
